FROM maven:3.2.2-openjdk-21 AS build
COPY . .   
RUN mvn clean package -DskipTests

FROM openjdk:21.0.1-jdk-slim
COPY --from=stage /target/assignment_1-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar" , "assignment_1.jar" ]
